var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //inter-region borders
		'mapShadow':'#000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'hoverShadow':'#666666', //tooltip shadow color
	},
	'map_1':{
		'hover': 'ABRUZZO',  //region hover content
		'url':'http://www.html5interactivemaps.com/', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'#EBECED', //region's color when page loads
		'overColor':'#99CC00', //region's color when mouse hover
		'downColor':'#99CC00',//region's color when mouse clicking
		'enable':true,//true/false to enable/disable this region
	},
	'map_2':{
		'hover': 'VALLE D&rsquo;AOSTA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_3':{
		'hover': 'PUGLIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_4':{
		'hover': 'BASILICATA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_5':{
		'hover': 'CALABRIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_6':{
		'hover': 'CAMPANIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_7':{
		'hover': 'EMILIA-ROMAGNA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_8':{
		'hover': 'FRIULI-VENEZIA GIULIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_9':{
		'hover': 'LAZIO',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_10':{
		'hover': 'LIGURIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_11':{
		'hover': 'LOMBARDIA',
		'url':'#',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':true,
	},
	'map_12':{
		'hover': 'MARCHE',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_13':{
		'hover': 'MOLISE',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_14':{
		'hover': 'PIEMONTE',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_15':{
		'hover': 'SARDEGNA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_16':{
		'hover': 'SICILIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_17':{
		'hover': 'TRENTINO-ALTO ADIGE',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_18':{
		'hover': 'TOSCANA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_19':{
		'hover': 'UMBRIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
	'map_20':{
		'hover': 'VENETO',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#99CC00',
		'downColor':'#993366',
		'enable':false,
	},
}